### ISSUE TITLE
Stopping Tika service / daemon

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/tika-server.deb#2]
Stopping the daemon with

service tika stop

and so

service tika restart

doesn't work.

**Comment by Mandalka** [comment]
Maybe problem in https://github.com/opensemanticsearch/tika-server.deb/blob/master/etc/init.d/tika which uses https://packages.debian.org/stable/daemon to daemonize Tika.

Maybe the respawn parameter?

Doc: http://www.libslack.org/daemon/#documentation

Prove if standard start scripts for Tika server available (i.e. like for Solr)

**Comment by opensemanticsearch** [comment]
Not caused by respawn.

Will be solved by https://github.com/opensemanticsearch/open-semantic-search/issues/181

**Comment by opensemanticsearch** [comment]
Solved by migration to systemd config in https://github.com/opensemanticsearch/tika-server.deb/commit/f84e849242c58b1ec425ae93ba1c00875abfc7d7
