### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by revolunet** [opensemanticsearch/tika-server.deb#5]
Hello

Looks like there's a slight install issue on ubuntu, here's my log (inside docker)

```sh
Step 10/10 : RUN dpkg -i tika-server.deb_17.06.23.deb || true
 ---> Running in 5e8104f43456
Selecting previously unselected package tika-server.
(Reading database ... 32271 files and directories currently installed.)
Preparing to unpack tika-server.deb_17.06.23.deb ...
Unpacking tika-server (1.15) ...
Setting up tika-server (1.15) ...
Adding system user `tika' (UID 108) ...
Adding new user `tika' (UID 108) with group `nogroup' ...
Creating home directory `/home/tika' ...
daemon: fatal: failed to find pid for tika: No such file or directory
dpkg: error processing package tika-server (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu21) ...
Errors were encountered while processing:
 tika-server
```

diggin'

**Comment by wizzed** [comment]
I have this problem as well.

**Comment by opensemanticsearch** [comment]
Within the next months there will be better/more separated Docker containers for the other components which will be better configurable for/over (distributed) network/servers by more usage of REST-interfaces instead local text config files, so an official Tika Docker container can be used without this custom deb package.

**Comment by opensemanticsearch** [comment]
For Tika this should be possible even today without this deb by Docker container https://github.com/LogicalSpark/docker-tikaserver since you can set the Tika Server URL to this container in /etc/opensemanticsearch/etl

**Comment by opensemanticsearch** [comment]
Will be solved by opensemanticsearch/open-semantic-search#181

**Comment by opensemanticsearch** [comment]
Solved by migration to systemd config in https://github.com/opensemanticsearch/tika-server.deb/commit/f84e849242c58b1ec425ae93ba1c00875abfc7d7
