### ISSUE TITLE
Error 500 if multiple OCR dictionaries

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/tika-server.deb#7]
Since upgrade to Tika 1.18 there is an server error 500 if multiple OCR dictionaries like eng+deu in headers instead of one (without plus).

**Comment by Mandalka** [comment]
Seems to be a Tika 1.18 issue, opened Bug report in [TIKA-2638](https://issues.apache.org/jira/browse/TIKA-2638)

**Comment by Mandalka** [comment]
Packages and builds (on build system not on Github) use Tika 1.17 until solved.

**Comment by Mandalka** [comment]
Fixed in Tika sources. Upgrade to newest Tika version on next relase.

**Comment by Mandalka** [comment]
In Tika 1.19.1 RC it works again.
